FROM php:8.2-fpm
RUN apt-get update && apt-get install -y \
    libmariadb-dev-compat \
    curl \
    net-tools \
    default-mysql-client \
    && docker-php-ext-install pdo_mysql \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /var/www
COPY backend .
RUN composer install --no-dev --optimize-autoloader
EXPOSE 9000