name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install frontend dependencies
        run: cd frontend && npm install
      - name: Build frontend
        run: cd frontend && npm run build
      - name: Run frontend tests
        run: cd frontend && npm test
        continue-on-error: true

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install backend dependencies
        run: cd backend && composer install --no-interaction
      - name: Create .env file
        run: |
          cd backend
          echo "APP_NAME=Laravel" > .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env
      - name: Generate app key
        run: cd backend && php artisan key:generate --force
      - name: Run backend tests
        run: cd backend && ./vendor/bin/phpunit
        continue-on-error: true